matrix:
  include:
    - language: python
      python: 3.7
      cache: pip
      install:
      - pip install matplotlib 
      - pip install scipy
      script:
      - python -c "print('Hello from Python!')"
      - python -m unittest discover -s tests
